import assert from 'node:assert/strict';
import fs from 'node:fs';
import '../assets/admin-core.js';
import {GitHubSimulation,TEST_KEY} from './github-simulation.mjs';
const C=globalThis.OpendoorCMS;
const original=JSON.parse(fs.readFileSync(new URL('../assets/content.json',import.meta.url),'utf8'));
let checks=0;
const check=(truth,message)=>{assert.ok(truth,message);checks++;};
check(C.validateContent(original,{publishing:true}).length===0,'Existing content remains valid');
const backend=new GitHubSimulation(original,{released:false});
const store=new C.GitHubStore(backend.fetch);
await assert.rejects(()=>store.login('a-shared-password'));checks++;
await assert.rejects(()=>store.login('github_pat_'+'wrong_'.repeat(8)));checks++;
await store.login(TEST_KEY);
const originalMain=backend.refs.get('main');
const data=C.clone(store.snapshot.data),editorial={pending:{}};
data.host.photo='assets/uploads/host-test.png';
data.strings.it.subtitle='Una casa accogliente, anche con accenti è e simboli < >.';
await store.save(data,editorial,[{path:data.host.photo,bytes:new Uint8Array([137,80,78,71])}]);
check(backend.refs.get('main')===originalMain,'Saving draft never changes the live site');
check(backend.files('content-draft').has(data.host.photo),'Upload and content commit together');
check(JSON.parse(backend.file('content-draft','assets/content.json')).host.photo===data.host.photo,'Uploaded profile is durable in the saved draft');
await assert.rejects(()=>store.publish(),/prima pubblicazione/i);checks++;
const another=new C.GitHubStore(backend.fetch);await another.login(TEST_KEY);
check(another.snapshot.data.strings.it.subtitle===data.strings.it.subtitle,'A new session reads saved Unicode content');
const priorDraft=backend.refs.get('content-draft');backend.failNext('/git/trees');
await assert.rejects(()=>another.save({...data,host:{...data.host,email:'host@example.test'}},editorial));checks++;
check(backend.refs.get('content-draft')===priorDraft,'Failure cannot expose partial content or media');
await store.save({...data,host:{...data.host,email:'owner@example.test'}},editorial);
await assert.rejects(()=>another.save(data,editorial),/altra sessione/);checks++;
const ready=new GitHubSimulation(original);
const publishStore=new C.GitHubStore(ready.fetch);await publishStore.login(TEST_KEY);
const changed=C.clone(original),pending={pending:{}};
C.changeText(changed,pending,'subtitle','it','Benvenuto a casa.');
check(C.pendingCount(pending)===6,'Italian changes require six translation reviews');
await publishStore.save(changed,pending);
await assert.rejects(()=>publishStore.publish(),/traduzioni/);checks++;
for(const lang of C.LANGUAGES.filter(code=>code!=='it'))C.changeText(changed,pending,'subtitle',lang,changed.strings[lang].subtitle+' ');
check(C.pendingCount(pending)===0,'Editing each translation clears its pending review');
changed.host.photo='assets/uploads/host-test.png';
await publishStore.save(changed,pending,[{path:changed.host.photo,bytes:new Uint8Array([137,80,78,71])}]);
const liveBefore=ready.refs.get('main'),liveIndex=ready.files('main').get('index.html');
check(ready.refs.get('main')===liveBefore,'Saving an activated site still changes only the draft');
await publishStore.publish();
check(JSON.parse(ready.file('main','assets/content.json')).strings.it.subtitle==='Benvenuto a casa.','Publishing exposes the reviewed content');
check(ready.files('main').get('index.html')===liveIndex,'Content publishing preserves live application code');
check(ready.files('main').has(changed.host.photo),'Publishing includes draft uploads');
check(ready.refs.get('main')===ready.refs.get('content-draft'),'After publishing, next draft starts from the published version');
const concurrency=new C.GitHubStore(ready.fetch);await concurrency.login(TEST_KEY);await concurrency.save(changed,pending);
const files=new Map(ready.files('main'));files.set('assets/content.json',ready.blob(JSON.stringify({...changed,property:{...changed.property,town:'Changed elsewhere'}})));ready.refs.set('main',ready.commit(ready.tree(files),[ready.refs.get('main')],'Other editor'));
await assert.rejects(()=>concurrency.publish(),/contenuti online sono cambiati/);checks++;
await assert.rejects(()=>concurrency.api('GET','/../../another-repo'));checks++;
const payload=C.clone(original);payload.strings.it.subtitle='</script><script>alert(1)</script>';
check(!C.scriptContent(payload).includes('</script>'),'Script serialization prevents an HTML breakout');
check(!C.mediaURL('javascript:alert(1)'),'Unsafe image URLs are rejected');
check(!C.mediaURL('assets/uploads/../admin.js'),'Traversal is rejected');
check(!C.mediaURL('https://example.test/watch?v=1',true),'A watch page cannot masquerade as a direct video');
check(C.mediaURL('https://example.test/guide.webm',true),'Direct WebM URLs are supported');
const privateContent=C.clone(original);privateContent.strings.it.subtitle=TEST_KEY;
check(C.validateContent(privateContent).length>0,'Secrets cannot be accidentally saved as public text');
store.logout();await assert.rejects(()=>store.api('GET',''));checks++;
check([...backend.calls,...ready.calls].every(call=>call.url.startsWith('https://api.github.com/repos/manubaba108/opendoor')),'Every request is confined to OPENDOOR');
console.log(JSON.stringify({checks,passed:true,scope:'OPENDOOR only',productionWrites:false}));
